# Fabricator object and at least one ControlNode are required
# For more configuration options see https://docs.githedgehog.com

apiVersion: fabricator.githedgehog.com/v1beta1
kind: Fabricator
metadata:
  name: default
  namespace: fab
spec:
  config:
    registry:
      mode: upstream
      upstream:
        repo: m.l.hhdev.io:30000
        prefix: githedgehog
        noTLSVerify: false
        username: lab
        password: HH.Labs!

    control:
      tlsSAN: # IPs and DNS names that will be used to access API
        - "env-1.l.hhdev.io"

      defaultUser: # user 'core' on all control nodes
        password: "$5$8nAYPGcl4l6G7Av1$Qi4/gnM0yPtGv9kjpMh78NuNSfQWy7vR1rulHpurL36" # password hash
        authorizedKeys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpF2+9I1Nj4BcN7y6DjzTbq1VcUYIRGyfzId5ZoBEFj"

    fabric:
      mode: spine-leaf # "spine-leaf" or "collapsed-core"
      includeONIE: true
      defaultSwitchUsers:
        admin: # at least one user with name 'admin' and role 'admin'
          role: admin
          password: "$5$8nAYPGcl4l6G7Av1$Qi4/gnM0yPtGv9kjpMh78NuNSfQWy7vR1rulHpurL36" # password hash
          authorizedKeys:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpF2+9I1Nj4BcN7y6DjzTbq1VcUYIRGyfzId5ZoBEFj"
        op: # optional read-only user
          role: operator
          password: "$5$8nAYPGcl4l6G7Av1$Qi4/gnM0yPtGv9kjpMh78NuNSfQWy7vR1rulHpurL36" # password hash
          authorizedKeys:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpF2+9I1Nj4BcN7y6DjzTbq1VcUYIRGyfzId5ZoBEFj"

      defaultAlloyConfig:
        agentScrapeIntervalSeconds: 15
        unixScrapeIntervalSeconds: 15
        unixExporterEnabled: true
        collectSyslogEnabled: true
        lokiTargets:
          lab:
            url: http://l.hhdev.io:32012/loki/api/v1/push
            useControlProxy: true
            labels:
              env: env-1
        prometheusTargets:
          lab:
            url: http://l.hhdev.io:32011/api/v1/push
            useControlProxy: true
            labels:
              env: env-1
            sendIntervalSeconds: 15

---
apiVersion: fabricator.githedgehog.com/v1beta1
kind: ControlNode
metadata:
  name: control-1
  namespace: fab
  annotations:
    link.hhfab.githedgehog.com/enp2s1: pci@0000:01:00.1
spec:
  bootstrap:
    disk: "/dev/sda" # disk to install OS on, e.g. "sda" or "nvme0n1"
  external:
    interface: enp2s0 # interface for external
    ip: dhcp # IP address for external interface
  management:
    interface: enp2s1 # interface for management

# Currently only one ControlNode is supported
