apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5248-01--mclag-domain--s5248-02
spec:
  mclagDomain:
    peerLinks:
      - switch1:
          port: s5248-01/E1/55/1
        switch2:
          port: s5248-02/E1/55/1
      - switch1:
          port: s5248-01/E1/55/2
        switch2:
          port: s5248-02/E1/55/2
    sessionLinks:
      - switch1:
          port: s5248-01/E1/55/3
        switch2:
          port: s5248-02/E1/55/3
      - switch1:
          port: s5248-01/E1/55/4
        switch2:
          port: s5248-02/E1/55/4
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-01--fabric--s5248-01
spec:
  fabric:
    links:
      - spine:
          port: s5232-01/E1/1
        leaf:
          port: s5248-01/E1/49
      - spine:
          port: s5232-01/E1/2
        leaf:
          port: s5248-01/E1/51
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-01--fabric--s5248-02
spec:
  fabric:
    links:
      - spine:
          port: s5232-01/E1/3
        leaf:
          port: s5248-02/E1/49
      - spine:
          port: s5232-01/E1/4
        leaf:
          port: s5248-02/E1/51
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-01--fabric--s5248-03
spec:
  fabric:
    links:
      - spine:
          port: s5232-01/E1/5
        leaf:
          port: s5248-03/E1/49
      - spine:
          port: s5232-01/E1/6
        leaf:
          port: s5248-03/E1/51
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-01--fabric--s5248-04
spec:
  fabric:
    links:
      - spine:
          port: s5232-01/E1/7
        leaf:
          port: s5248-04/E1/49
      - spine:
          port: s5232-01/E1/8
        leaf:
          port: s5248-04/E1/51
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-02--fabric--s5248-01
spec:
  fabric:
    links:
      - spine:
          port: s5232-02/E1/1
        leaf:
          port: s5248-01/E1/53
      - spine:
          port: s5232-02/E1/2
        leaf:
          port: s5248-01/E1/54
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-02--fabric--s5248-02
spec:
  fabric:
    links:
      - spine:
          port: s5232-02/E1/3
        leaf:
          port: s5248-02/E1/53
      - spine:
          port: s5232-02/E1/4
        leaf:
          port: s5248-02/E1/54
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-02--fabric--s5248-03
spec:
  fabric:
    links:
      - spine:
          port: s5232-02/E1/5
        leaf:
          port: s5248-03/E1/53
      - spine:
          port: s5232-02/E1/6
        leaf:
          port: s5248-03/E1/54
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5232-02--fabric--s5248-04
spec:
  fabric:
    links:
      - spine:
          port: s5232-02/E1/7
        leaf:
          port: s5248-04/E1/53
      - spine:
          port: s5232-02/E1/8
        leaf:
          port: s5248-04/E1/54
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5248-01--vpc-loopback
spec:
  vpcLoopback:
    links:
      - switch1:
          port: s5248-01/E1/17
        switch2:
          port: s5248-01/E1/18
      - switch1:
          port: s5248-01/E1/19
        switch2:
          port: s5248-01/E1/20
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5248-02--vpc-loopback
spec:
  vpcLoopback:
    links:
      - switch1:
          port: s5248-02/E1/17
        switch2:
          port: s5248-02/E1/18
      - switch1:
          port: s5248-02/E1/19
        switch2:
          port: s5248-02/E1/20
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5248-03--vpc-loopback
spec:
  vpcLoopback:
    links:
      - switch1:
          port: s5248-03/E1/17
        switch2:
          port: s5248-03/E1/18
      - switch1:
          port: s5248-03/E1/19
        switch2:
          port: s5248-03/E1/20
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: s5248-04--vpc-loopback
spec:
  vpcLoopback:
    links:
      - switch1:
          port: s5248-04/E1/17
        switch2:
          port: s5248-04/E1/18
      - switch1:
          port: s5248-04/E1/19
        switch2:
          port: s5248-04/E1/20
##
## Servers
##
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-1
spec:
  description: MCLAG s5248-01/E1 s5248-02/E1
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-1--mclag--s5248-01--s5248-02
spec:
  mclag:
    links:
      - server:
          port: server-1/enp2s1
        switch:
          port: s5248-01/E1/2
      - server:
          port: server-1/enp2s2
        switch:
          port: s5248-02/E1/2
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-2
spec:
  description: MCLAG s5248-01/E2 s5248-02/E2
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-2--mclag--s5248-01--s5248-02
spec:
  mclag:
    links:
      - server:
          port: server-2/enp2s1
        switch:
          port: s5248-01/E1/3
      - server:
          port: server-2/enp2s2
        switch:
          port: s5248-02/E1/3
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-3
spec:
  description: SH LAG s5248-01/E3-4
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-3--bundled--s5248-01
spec:
  bundled:
    links:
      - server:
          port: server-3/enp2s1
        switch:
          port: s5248-01/E1/4
      - server:
          port: server-3/enp2s2
        switch:
          port: s5248-01/E1/5
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-4
spec:
  description: SH s5248-02/E3
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-4--unbundled--s5248-02
spec:
  unbundled:
    link:
      server:
        port: server-4/enp2s1
      switch:
        port: s5248-02/E1/4
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-5
spec:
  description: ESLAG s5248-03/E2 s5248-04/E2
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-5--eslag--s5248-03--s5248-04
spec:
  eslag:
    links:
      - server:
          port: server-5/enp2s1
        switch:
          port: s5248-03/E1/3
      - server:
          port: server-5/enp2s2
        switch:
          port: s5248-04/E1/3
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-6
spec:
  description: ESLAG s5248-03/E41 s5248-04/E39
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-6--eslag--s5248-03--s5248-04
spec:
  eslag:
    links:
      - server:
          port: server-6/enp2s1
        switch:
          port: s5248-03/E1/42
      - server:
          port: server-6/enp2s2
        switch:
          port: s5248-04/E1/40
# ---
# apiVersion: wiring.githedgehog.com/v1beta1
# kind: Server
# metadata:
#   name: server-7
# spec:
#   description: SH LAG s5248-03/E0-1
# ---
# apiVersion: wiring.githedgehog.com/v1beta1
# kind: Connection
# metadata:
#   name: server-7--bundled--s5248-03
# spec:
#   bundled:
#     links:
#       - server:
#           port: server-7/enp2s1
#         switch:
#           port: s5248-03/E1/1
#       - server:
#           port: server-7/enp2s2
#         switch:
#           port: s5248-03/E1/2
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-7
spec:
  description: SH s5248-03/E0
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-7--unbundled--s5248-03
spec:
  unbundled:
    link:
      server:
        port: server-7/enp2s1
      switch:
        port: s5248-03/E1/1
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-8
spec:
  description: SH s5248-03/E1
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-8--unbundled--s5248-03
spec:
  unbundled:
    link:
      server:
        port: server-8/enp2s1
      switch:
        port: s5248-03/E1/2
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Server
metadata:
  name: server-9
spec:
  description: SH s5248-04/E1
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: server-9--unbundled--s5248-04
spec:
  unbundled:
    link:
      server:
        port: server-9/enp2s1
      switch:
        port: s5248-04/E1/2
